name: Generate Datas

on:
  schedule: # execute every 24 hours
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: generate python_bem_boiola.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/python_bem_boiola.svg?palette=github-dark&color_snake=#ff33ff&color_dots=#1b2994,#9999ff,#6666ff,#3333ff,#0000FF

          
          
      - name: push python_bem_boiola.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
